In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt


individuos=10
N=individuos
bits = 10


X = np.zeros([N,bits])

for i in range(N):
  for j in range (bits):
    X[i,j]=random.randint(0,1)


numDec  = np.zeros(N)
T = 0

for p in range(N):
  for u in range(bits):
    if X[p,u]==1:
      numDec[p] += 2**(9-u)  
  T += numDec[p] 
  
r = np.zeros(N)

for j in range (N):
   r[j] = random.randint(1,T)


print(X)
print('individuos: ',numDec)
print('T:          ',T)
print('r:          ',r)

indiv = numDec[0]
padreGana1 = np.zeros(N)

for b in range(N):
  i=0
  while indiv < r[b]:
    indiv += numDec[i+1]
    i += 1
  padreGana1[b] = numDec[i]
  print('padreRuleta = ',padreGana1[b])  
  indiv=numDec[0]

print('VecPadreRuleta ',padreGana1 )
  

[[0. 0. 1. 0. 1. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 1. 0.]]
individuos:  [172.  98. 522. 860. 602. 139. 998. 274. 138. 122.]
T:           3925.0
r:           [ 986. 2176. 2951. 2300. 3841. 2563. 3438.  258. 1571. 3392.]
padreRuleta =  860.0
padreRuleta =  602.0
padreRuleta =  998.0
padreRuleta =  139.0
padreRuleta =  122.0
padreRuleta =  998.0
padreRuleta =  274.0
padreRuleta =  98.0
padreRuleta =  860.0
padreRuleta =  274.0
VecPadreRuleta  [860. 602. 998. 139. 122. 998. 274.  98. 860. 274.]


In [ ]:

padreGana = np.zeros(N)

for i in range(N):
  J = np.random.randint(0,9)
  H = np.random.randint(0,9)
  # print(J,H)
  padre_1 = numDec[J]
  padre_2 = numDec[H]
  # print(padre_1)
  # print(padre_2)
  if padre_1<padre_2:
      padreGana[i] = padre_2
  elif padre_1 == padre_2:
     padreGana[i] = padre_1
  else:
     padreGana[i] = padre_1
  print('PadreTorneo = ',padreGana[i])


print('VecPadreTorneo: ', padreGana)
print('VecPadreRuleta: ', padreGana1)




PadreTorneo =  522.0
PadreTorneo =  522.0
PadreTorneo =  522.0
PadreTorneo =  860.0
PadreTorneo =  139.0
PadreTorneo =  274.0
PadreTorneo =  522.0
PadreTorneo =  139.0
PadreTorneo =  860.0
PadreTorneo =  172.0
VecPadreTorneo:  [522. 522. 522. 860. 139. 274. 522. 139. 860. 172.]
VecPadreRuleta:  [860. 602. 998. 139. 122. 998. 274.  98. 860. 274.]


In [ ]:
frecc = {}
frecc2 = {}
for n in padreGana:
  if n in frecc:
    frecc[n] += 1
  else:
    frecc[n] = 1

for n in padreGana1:
  if n in frecc2:
    frecc2[n] += 1
  else:
    frecc2[n] = 1

print('FrecuanciaPorTorneo',frecc)
print('FrecuenciaPorRuleta',frecc2)

equals = np.zeros(N)
i = 0
for g in padreGana:
  if g in padreGana1:
    equals[i] = g
    i +=1


print(equals)

FrecuanciaPorTorneo {28.5: 2, 14.0: 3}
FrecuenciaPorRuleta {970.0: 2, 851.0: 2, 787.0: 2, 650.0: 1, 1013.0: 2, 213.0: 1}
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.

In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt


    
X =  [[1,0, 0, 1, 1, 0, 1, 0, 0, 0],
     [0, 0, 1, 1, 1, 1, 1, 0, 1, 0],
     [1, 1, 0, 1, 0, 0, 0, 1, 1, 1],
     [1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
     [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
     [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
     [1, 0, 0, 1, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]]
X = np.array(X)
A = np.zeros(8)


print(X)
cont =0
for i in range(8):
  for j in range(10):
    if X[i,j] == 1:
      cont = cont +1
  A[i] = cont
  cont = 0
print(A)

r = [5,20,2,40,27,38,42,1,15,30]
r = np.array(r)
i = 0

sum = A[i]
cont1 = 1  


for k in range(10):
  while sum < r[k]:
    sum = sum + A[i+1]
    i += 1
    cont1 += 1
  sum = A[0]
  i = 0
  print(cont1)
  cont1 = 1



[[1 0 0 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 0]
 [1 1 0 1 0 0 0 1 1 1]
 [1 0 1 1 0 0 0 1 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [1 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 0 0 1]]
[4. 6. 6. 4. 8. 9. 8. 2.]
2
4
1
7
5
7
7
1
3
6


In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt

individuos=500
N=individuos
bits = 10


X = np.zeros([N,bits])

for i in range(N):
  for j in range (bits):
    X[i,j]=random.randint(0,1)
  
index = np.zeros([N,bits])
peso = [25,20,20,12.5,10,10,7.5,4,1,1]
monedas = [5000,2500,10,2500,2500,200,3000,500,100,10]

z = peso*X
y = monedas*X
sumPesos = np.zeros(N)
sumMone = np.zeros(N)
print(X)

for k in range(N):
  for h in range(bits):
    sumPesos[k]= sumPesos[k] + z[k,h]
    sumMone[k]= sumMone[k] + y[k,h]

# print(sumPesos)
# print(sumMone)  
padres = []

for c in range(N):
  if sumPesos[c] <= 30:
    padres.append(c)


print(padres)



[[0. 0. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 1. 1. 1.]]
[6, 8, 12, 13, 27, 39, 58, 59, 79, 80, 84, 87, 90, 94, 97, 99, 123, 124, 134, 147, 148, 152, 157, 165, 168, 175, 176, 212, 216, 225, 232, 238, 240, 242, 263, 278, 288, 290, 296, 297, 317, 330, 332, 344, 358, 366, 369, 385, 391, 397, 399, 400, 408, 412, 415, 422, 430, 439, 461, 479, 489, 497]


In [ ]:
padrePesos = []

#Selección de padres por peso
for i in range(N):
  J = np.random.randint(0,N-1)
  H = np.random.randint(0,N-1)

  padrePesos_1 = sumPesos[J]
  padrePesos_2 = sumPesos[H]

  if padrePesos_1 < padrePesos_2:
    padrePesos.append(J)
  else:
    padrePesos.append(H)


nvaPobla = []
for b in padrePesos:
  nvaPobla.append(X[b])

nvaPobla = np.array(nvaPobla)
padreMone = []

#Selección de padres por moneda
for a in range(N):
  J = np.random.randint(0,N-1)
  H = np.random.randint(0,N-1)

  padreMone_1 = sumMone[J]
  padreMone_2 = sumMone[H]

  if padreMone_1 >= padreMone_2:
    padreMone.append(J)
  else:
    padreMone.append(H)

nvaPobla2 = []
for b in padreMone:
  nvaPobla2.append(X[b])

#print(nvaPobla2)
v = len(nvaPobla2)
proRecom = round(v*0.7)
#print(v,proRecom)
PobsinDes = nvaPobla2
print(nvaPobla2)

del(PobsinDes[0:proRecom])
del(nvaPobla2[proRecom:v])
#print(PobsinDes)
print(nvaPobla2)
totalpobla = nvaPobla2+PobsinDes


#print(totalpobla)



nvaPobla2 = np.array(nvaPobla2)
for j in range(proRecom):
  ra = random.randint(1,bits-1)



# print(ra)
# print(  nvaPobla2[j,(ra, 0)])


[array([1., 1., 1., 0., 1., 0., 1., 0., 0., 0.]), array([1., 0., 1., 1., 1., 1., 1., 1., 0., 0.]), array([1., 1., 1., 1., 0., 1., 0., 1., 0., 1.]), array([1., 1., 1., 1., 1., 0., 1., 1., 0., 1.]), array([1., 0., 1., 0., 1., 1., 1., 0., 1., 1.]), array([1., 0., 1., 0., 0., 0., 0., 0., 0., 1.]), array([0., 1., 0., 1., 1., 1., 1., 1., 0., 1.]), array([1., 1., 0., 0., 1., 1., 0., 0., 1., 1.]), array([1., 1., 0., 0., 1., 1., 1., 1., 0., 0.]), array([0., 1., 0., 1., 0., 1., 0., 0., 1., 1.]), array([1., 1., 1., 1., 1., 0., 1., 0., 1., 0.]), array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0.]), array([1., 0., 0., 0., 0., 1., 0., 1., 1., 0.]), array([0., 1., 0., 1., 0., 0., 0., 1., 1., 1.]), array([1., 1., 1., 1., 1., 0., 0., 0., 1., 1.]), array([1., 1., 1., 1., 1., 0., 0., 1., 1., 1.]), array([0., 1., 0., 1., 0., 0., 1., 1., 1., 0.]), array([0., 1., 0., 0., 1., 1., 1., 1., 1., 1.]), array([0., 1., 0., 0., 1., 1., 1., 1., 1., 1.]), array([1., 1., 0., 0., 0., 1., 1., 1., 1., 1.]), array([1., 1., 0., 

In [ ]:
print(X[291])

[0. 1. 1. 0. 0. 0. 0. 1. 1. 1.]


In [ ]:
0. 1. 0. 0. 1. 0. 0. 1. 1. 1.
